### ISSUE TITLE
Blocking Error

### ISSUE THREAD

**Issue by nosizejosh** [LBBLUG/meteorBastas#2]
Hello there, I tried to run a copy of your project to learn how you implement theback with ui, but i am gettingthis error that is preventing me from running. Im using windows. please help. 

ps: There was an ealire error with imports which i fixed

> import { BastasDB } from '/imports/api/bastasDb.js';

see the blocking error below

![image](https://cloud.githubusercontent.com/assets/392227/24419544/5f729294-13e7-11e7-85f0-6044cb7fcf44.png)

**Comment by bmcgonag** [comment]
No problem, sorry you're having trouble, but if you're running your server
portion of meteor on Windows, this solution won't work.  I use ShellJS to
run the bash shell commands in the background.

ShellJS is for unix shell commands, and I'm guessing, unless you can make
windows default to BASH using the newer Linux underpinnings available in
Windows 10.

Brian McGonagill

**Comment by bmcgonag** [comment]
@nosizejosh  Sorry, so it may work on Windows, but do you have MongoDB installed separate from Meteor?

I'm going to try in a bit, but need to get to a Windows machine.

**Comment by nosizejosh** [comment]
I just commented out the shelljs import statement line to clear the errors and I tried the backup , i got success feedback but not sure here to locate the backup to be certain it actually worked. I just copied the example file path you have, ` /home/brian/myMeteorBackup` so where will the backup be?

**Comment by bmcgonag** [comment]
You have to provide the path (on the server) in the UI where you want the backup to be made. 

I noticed you changed the import statement, which is fine.  I believe I've updated that and not committed yet, but if you look at the 'Server' directory, you'll see 'MyMethods.js', and that's where I'm running the backup from rather than from the imports/api/bastasDB.js. 

I found that again, the backup must be run on the server as that is where the DB lives in actuality, so the method is called on the server only. 

If you are running meteor on your local machine, then the backup (if it ran) should be in the path you specify.  Again, my example is made for Mac / Linux based directory structure, so, you may have to modify the path to fit the directory structure of Windows.

In the code, I'm building the output path based on user input, and the current date / time.  That allows my user to run the backup multiple times, without overwriting a previous backup.

**Comment by nosizejosh** [comment]
Ok Thanks will check on it. Lastly, is there a way to restore backed-up data?

**Comment by bmcgonag** [comment]
@nosizejosh  Restore in a similar fashion with MongoImport, check out their documentation, but I would just build a file picker, then use that as an argument in the command. 

Just FYI, on windows I had to change into the MongoDB/Server/3.4/bin directory to run the mongodump.exe command.  So you may need to add that to your path if you want to run it from anywhere. 

Once I got there I was able to run the following (as and example)

`mongodump -h 127.0.0.1 --port 3001 --out "C:\Users\<username>\Documents\testDump" -d meteor`

and it ran successfully and backed up the data.  You would of course change <username> to the actual username for that windows user, or pick a path that your mongodump command can access. 

Hope it helps,

**Comment by nosizejosh** [comment]
I appreciate your help. Will try them your suggestions out and revert. Thanks!

**Comment by bmcgonag** [comment]
@nosizejosh I just want to make sure I'm clear.  The ShellJS library is what I'm using to allow the application to access the command line tool mongodump.  If you don't use / import ShellJS it won't work.  You may get a 'Success' message because of what I'm looking for, but in reality nothing will be dumped.  

If you install ShellJS globally, you may not have to import it, but I haven't tried to run that way.
